In [1]:
import scipy as sc
import numpy as np
import pandas as pd
from scipy.stats import ks_2samp

In [2]:
data_dir = 'https://github.com/henrii1/WTPCM-using-multivariate-DM-and-K-S-test/blob/main/Dataset/k_s_data.xlsx?raw=true'
dat = pd.read_excel(data_dir)
data = np.array(dat)
data

array([[1905.50061035, 2014.80505371, 2042.95495605, ..., 2032.02880859,
        1998.73095703, 2042.95495605],
       [1942.29382324, 2045.39318848, 2044.49157715, ..., 2016.88537598,
        1951.82043457, 2044.49157715],
       [1866.86218262, 2049.99316406, 2033.0880127 , ..., 2045.43225098,
        1957.94250488, 2033.0880127 ],
       ...,
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan]])

In [3]:
A = data[:2937, 0]
A

array([1905.50061035, 1942.29382324, 1866.86218262, ..., 2012.60107422,
       2014.97814941, 2029.78881836])

In [4]:
B = data[:65, 1]
B

array([2014.80505371, 2045.39318848, 2049.99316406, 2046.18151855,
       2026.80212402, 2010.92687988, 2030.94360352, 1981.31188965,
       2003.14807129, 1974.51477051, 1989.42529297, 2005.35668945,
       2004.45092773, 1939.75817871, 1990.1027832 , 2005.1887207 ,
       1977.59716797, 2022.13317871, 2033.27783203, 1892.21166992,
       1954.75244141, 1898.49108887, 1919.64086914, 1953.76257324,
       1944.1439209 , 1951.48376465, 1953.49365234, 1982.12353516,
       1965.49890137, 1915.15380859, 1902.66711426, 1982.0291748 ,
       1967.37097168, 1970.71203613, 1975.11816406, 1969.9329834 ,
       1908.25866699, 1889.88757324, 1971.20629883, 1935.73449707,
       1984.2890625 , 1988.1953125 , 2000.43359375, 2003.36901855,
       1946.42932129, 2028.90002441, 2010.02307129, 2002.44104004,
       2008.77380371, 2038.13635254, 2024.09899902, 2026.94506836,
       2026.45129395, 1966.18859863, 2047.07397461, 1971.3704834 ,
       1978.57434082, 1964.83520508, 1945.16210938, 1985.60668

In [5]:
C = data[:65, 2]
C

array([2042.95495605, 2044.49157715, 2033.0880127 , 2049.85180664,
       2057.83959961, 2049.06982422, 2061.19628906, 2047.19238281,
       2050.71923828, 2031.38903809, 2051.52685547, 2049.44824219,
       2036.28881836, 2041.9342041 , 2052.26879883, 2057.07373047,
       2051.25976562, 2047.48974609, 2046.97070312, 2051.55664062,
       2041.68518066, 2060.66894531, 2045.41333008, 2039.29504395,
       2070.83837891, 2050.20629883, 2070.16821289, 2004.63171387,
       2038.5489502 , 2029.25842285, 2032.39416504, 2027.30957031,
       2036.17077637, 2045.54919434, 2033.26220703, 2058.28662109,
       2030.24584961, 2063.48950195, 2044.4296875 , 2050.65625   ,
       2024.22106934, 2055.38696289, 2048.26635742, 2034.32763672,
       2042.81176758, 2030.93334961, 2016.22595215, 2045.33654785,
       2034.80944824, 2039.25109863, 2049.85546875, 2040.70727539,
       2050.87988281, 2047.18261719, 2065.72387695, 2045.92602539,
       2035.36413574, 2040.09655762, 2039.74389648, 2055.94848

In [6]:
D = data[:68, 3]
D

array([2003.87414551, 2015.20324707, 2008.54919434, 2008.65209961,
       2008.45178223, 2009.2980957 , 2021.02990723, 2025.00476074,
       2018.01257324, 2013.73547363, 2038.81396484, 2012.30871582,
       2015.58605957, 2024.48217773, 2026.08752441, 2006.89709473,
       2004.50268555, 2017.81506348, 2038.94616699, 2031.28161621,
       2028.07580566, 2022.22241211, 2033.97924805, 2029.38684082,
       2026.99597168, 2041.51501465, 2047.05322266, 2033.07775879,
       2037.02148438, 2038.15930176, 2027.00805664, 2033.86486816,
       2045.6817627 , 2051.44262695, 2040.0567627 , 2023.30969238,
       2036.52380371, 2038.31481934, 2035.00634766, 2026.29333496,
       2035.90795898, 2046.70666504, 2029.4296875 , 2042.92358398,
       2048.81982422, 2036.50219727, 2014.42016602, 2014.54211426,
       2027.02416992, 2020.1932373 , 2021.53527832, 2041.        ,
       2014.04907227, 2022.4453125 , 2013.96276855, 1990.83081055,
       1994.03369141, 1975.73803711, 1999.6184082 , 1992.44445

In [7]:
E = data[:3015, 4]
E

array([2009.75964355, 2009.8848877 , 2024.39367676, ..., 1988.03100586,
       1982.97314453, 2026.9666748 ])

In [8]:
F = data[:65, 5]
F

array([2014.26513672, 1972.66333008, 2019.12988281, 1962.82824707,
       1971.9642334 , 1988.00671387, 1992.74377441, 1996.7166748 ,
       2026.18994141, 2017.06237793, 2022.41650391, 2035.72119141,
       2036.60852051, 2035.7154541 , 2024.33105469, 2037.05541992,
       2015.13378906, 2039.17492676, 2031.8873291 , 2034.67834473,
       2050.04785156, 2019.73144531, 2017.15563965, 2048.28466797,
       2034.08276367, 2044.68286133, 2052.25976562, 2035.41271973,
       2046.22949219, 2059.23291016, 1991.23339844, 2034.62841797,
       1980.83056641, 2025.87731934, 2016.55725098, 1997.01000977,
       2029.34802246, 2015.57116699, 1989.08874512, 2019.34265137,
       2051.77270508, 2027.53894043, 2012.56970215, 2026.05932617,
       2040.02978516, 1955.70178223, 2031.68518066, 2045.43762207,
       2037.38317871, 2035.33728027, 2019.88061523, 2019.53942871,
       2010.95605469, 2040.16564941, 2051.63818359, 2018.27832031,
       2045.20336914, 2065.06591797, 2059.38305664, 2048.23583

In [9]:
G = data[:65, 6]
G

array([2032.02880859, 2016.88537598, 2045.43225098, 2041.04064941,
       2014.0357666 , 2043.56665039, 2037.55212402, 2039.0456543 ,
       2032.83740234, 2037.36291504, 2037.55517578, 2044.41845703,
       2038.33740234, 2041.34130859, 2016.84887695, 2033.36340332,
       2044.76013184, 2031.50708008, 2016.80419922, 2062.58032227,
       2053.04345703, 2040.4432373 , 2023.59069824, 2027.5489502 ,
       2003.18530273, 2006.74450684, 2014.82800293, 1999.10400391,
       2005.94445801, 2003.87414551, 2015.20324707, 2008.54919434,
       2008.65209961, 2008.45178223, 2009.2980957 , 2021.02990723,
       2025.00476074, 2018.01257324, 2013.73547363, 2038.81396484,
       2012.30871582, 2015.58605957, 2024.48217773, 2026.08752441,
       2006.89709473, 2004.50268555, 2017.81506348, 2038.94616699,
       2031.28161621, 2028.07580566, 2022.22241211, 2033.97924805,
       2029.38684082, 2026.99597168, 2041.51501465, 2047.05322266,
       2033.07775879, 2037.02148438, 2038.15930176, 2027.00805

In [10]:
H = data[:65, 7]
H

array([1998.73095703, 1951.82043457, 1957.94250488, 1934.35119629,
       1966.1907959 , 2008.03051758, 1917.08618164, 1961.39501953,
       1992.49523926, 1857.09277344, 2007.5949707 , 1991.67443848,
       2001.06945801, 2017.19641113, 2005.01220703, 1997.65393066,
       1936.15649414, 1965.70349121, 1979.07202148, 1947.09667969,
       1953.24865723, 1945.94165039, 1992.72167969, 1963.13305664,
       1891.05517578, 1943.94018555, 1981.78540039, 1977.9387207 ,
       1971.80029297, 1990.48217773, 2014.33581543, 1951.30065918,
       1952.88549805, 1994.28308105, 1969.1114502 , 2018.0703125 ,
       2004.2454834 , 1950.31384277, 1952.64001465, 1984.08666992,
       1980.85583496, 1998.39245605, 1975.11682129, 1979.4901123 ,
       1956.98901367, 1951.23254395, 1946.45861816, 1984.29528809,
       1922.07800293, 1910.93151855, 2000.75      , 1939.26098633,
       1809.37768555, 1881.83239746, 1882.55969238, 2010.9354248 ,
       2004.63293457, 1982.05651855, 1928.27368164, 1937.40393

In [11]:
I = data[:1377, 8]
I

array([2042.95495605, 2044.49157715, 2033.0880127 , ..., 2042.83972168,
       2045.87585449, 2051.13476562])

In [12]:
sc.stats.ks_2samp(A, B, alternative='two-sided')

KstestResult(statistic=0.08768235509808543, pvalue=0.6788814342058427)

In [13]:
sc.stats.ks_2samp(I, C, alternative='two-sided')

KstestResult(statistic=0.045986257750963634, pvalue=0.9986177765457991)

In [14]:
sc.stats.ks_2samp(E, F, alternative = 'two-sided')

KstestResult(statistic=0.08312284730195178, pvalue=0.7394264138296116)

In [15]:
sc.stats.ks_2samp(E, G, alternative = 'two-sided')

KstestResult(statistic=0.12356167878555938, pvalue=0.2630317632508018)

In [16]:
sc.stats.ks_2samp(A, H, alternative = 'two-sided')

KstestResult(statistic=0.2281501270265315, pvalue=0.002159840250838485)

In [18]:
sc.stats.ks_2samp(E, D, alternative = 'two-sided')

KstestResult(statistic=0.17875816993464053, pvalue=0.02481934294145194)