In [18]:
import scipy as sc
import numpy as np
import pandas as pd
from scipy.stats import ks_2samp

In [19]:
data_dir = 'https://github.com/henrii1/WTPCM-using-multivariate-DM-and-K-S-test/blob/main/Dataset/k_s_data.xlsx?raw=true'
dat = pd.read_excel(data_dir)
data = np.array(dat)
data

array([[1905.50061035, 2054.6960899 ,   -4.18050604, ..., 2023.56906128,
        2042.72831624, 2042.95495605],
       [1942.29382324, 2031.63066406,   -2.43329353, ..., 2014.20521282,
        2035.8229248 , 2044.49157715],
       [1866.86218262, 2058.6423645 ,  275.1954704 , ..., 2036.06266683,
        2046.67962646, 2033.0880127 ],
       ...,
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan],
       [          nan,           nan,           nan, ...,           nan,
                  nan,           nan]])

In [20]:
A = data[:2937, 0]
A

array([1905.50061035, 1942.29382324, 1866.86218262, ..., 2012.60107422,
       2014.97814941, 2029.78881836])

In [21]:
B = data[:65, 1]
B

array([2054.6960899 , 2031.63066406, 2058.6423645 , 2039.49440308,
       2001.71698608, 1986.23595581, 2042.2602356 , 2061.69098511,
       2039.24681396, 2013.70498657, 2024.79554443, 2054.34527588,
       2050.10532227, 2061.3180481 , 2036.22432251, 2062.32676295,
       2035.70255127, 2044.73206787, 2038.18400269, 2061.08009644,
       2029.97026978, 2005.03665161, 1927.97038574, 2052.78096313,
       2045.10078125, 2043.70021362, 2038.50923237, 2037.54539795,
       2053.94086914, 2045.78575439, 2033.75287543, 2011.48438721,
       2051.38684082, 2057.29465942, 2040.22532349, 2051.83769531,
       2052.98638306, 2061.93746948, 2034.12701416, 2059.48215332,
       2047.15003662, 2047.23224487, 2047.22954102, 2014.03148193,
       1949.95090332, 2047.47125244, 2009.90783081, 2042.94487562,
       2045.73193359, 2008.45230103, 2043.20513306, 1994.05063477,
       2044.26897583, 2035.6539917 , 2059.12947388, 2038.20748901,
       2076.9759136 , 2039.91330438, 2036.83540853, 2023.22906

In [22]:
C = data[:65, 2]
C

array([  -4.18050604,   -2.43329353,  275.1954704 , 2047.43602905,
       2036.16029663, 2062.324823  , 2022.12201538, 2031.69985199,
       2051.44659065, 2031.13497925, 2022.65073242, 2024.86435547,
       2038.88294067, 2040.8105835 , 2072.23412476, 2027.0043457 ,
       2053.70557861, 2049.41173706, 2050.35592491, 2062.20431358,
       2055.43955688, 2042.40344238, 2036.81923828, 2032.0211792 ,
       2047.03536987, 2067.91838989, 2034.74113159, 2052.13626902,
       2034.04697876, 2037.36022339, 2044.38101196, 2048.22885742,
       2053.3107666 , 2043.54917506, 2039.74779053, 2043.44091187,
       2046.29622396, 2059.56897554, 2044.57251587, 2047.19380493,
       2027.05020752, 2019.47833252, 2027.92843628, 2035.5749939 ,
       2062.78311768, 2007.85264282, 2022.07129517, 1992.5572937 ,
       1995.42556152, 1968.56157769, 2029.20948551, 2027.96212608,
       2013.89329224, 1990.94655151, 2027.67443848, 2017.22097168,
       2020.98717651, 2020.64199219, 1976.37503855, 2029.90306

In [23]:
D = data[:3349, 3]
D

array([1578.96936035, 1500.99035645, 1519.4107666 , ..., 1880.79943848,
       1861.06018066, 1925.61376953])

In [24]:
E = data[:3015, 4]
E

array([2009.75964355, 2009.8848877 , 2024.39367676, ..., 1988.03100586,
       1982.97314453, 2026.9666748 ])

In [25]:
F = data[:65, 5]
F

array([1371.07680461, 1465.34542643, 1827.21810041, 1644.6088783 ,
       1681.35191127, 1974.02798697, 1945.04973687, 2016.18751221,
       1976.59254964, 1918.08417379, 1910.2394694 , 1811.41733398,
       1726.3713623 , 1849.36329346, 1863.84873047, 1847.53114827,
       1841.33371077, 1954.38284617, 2037.05835833, 1959.75600023,
       2020.98395996, 2006.01353455, 2063.44727434, 2031.38573767,
       2054.34047852, 1896.13249919, 1981.45589193, 1875.53631999,
       2036.98249512, 1983.37694906, 2051.38258464, 2024.94419352,
       2007.21845296, 1971.03988851, 2038.37892253, 1956.44929873,
       1917.47596436, 1817.80157064, 1533.38730876, 1944.18748122,
       2062.08916423, 1903.87939453, 2014.90383301, 1927.96912842,
       1665.29814046, 1711.29192912, 1760.599803  , 1854.79752744,
       1782.4446818 , 1927.88839518, 1951.01210124, 1896.20825195,
       1939.36687826, 2031.44122721, 1874.75271403, 1841.14581299,
       1726.16686198, 1779.32137858,  853.40144656,   -3.29382

In [26]:
G = data[:65, 6]
G

array([2023.56906128, 2014.20521282, 2036.06266683, 2040.12502441,
       2020.94269613, 2022.89150391, 2033.731486  , 2042.56478446,
       2036.61434733, 2032.30157681, 2033.61296555, 2027.90045797,
       2050.02918701, 2013.57779948, 2041.77931722, 2023.51399333,
       2007.54147949, 1958.16075439, 2014.14153842, 2034.32514242,
       2042.63261312, 2037.63556315, 2046.20516764, 2026.67035726,
       2027.55139567, 2026.60241699, 1998.66374919, 2036.78618753,
       2011.08690999, 2057.40794271, 2042.1207723 , 2029.2906901 ,
       2047.0122111 , 2035.30185954, 2035.73545329, 2042.23638102,
       2020.49736735, 2031.84990234, 2018.15587158, 2038.77338053,
       1932.49742839, 1978.11347249, 2019.13152262, 2007.91307373,
       1941.92850749, 2044.95666911, 2034.17327474, 1917.22734782,
       1997.11472575, 1966.01291097, 1959.56392008, 1962.37316081,
       2016.66268311, 2016.65372576, 2048.8256415 , 1959.94516695,
       1639.49254456, 1765.72024852, 2032.37064209, 1905.38255

In [27]:
H = data[:65, 7]
H

array([2042.72831624, 2035.8229248 , 2046.67962646, 2030.90366473,
       2047.53487843, 2048.14328206, 2050.75012614, 2053.32463786,
       2050.99718299, 2050.75409567, 2047.37038981, 2047.20356852,
       2053.05181478, 2050.6444987 , 2044.46867269, 2035.20013021,
       2025.83981527, 2043.85264486, 2023.33041585, 2038.56564128,
       2027.79075521, 2025.4565135 , 2017.10907389, 1990.35909017,
       1995.49      , 1993.        , 2000.        , 2010.        ,
       2015.08683268, 2005.86534831, 2010.63514404, 2020.2728597 ,
       2025.91144206, 2028.78431396, 2030.63341064, 2020.58748372,
       2018.04829915, 2020.55424398, 2019.94737142, 2015.82141113,
       2015.68243408, 2003.82602801, 2022.99688314, 2030.61825765,
       2035.49532878, 2034.8543986 , 2025.29671224, 2040.47537126,
       2028.26218356, 2030.02856852, 2034.87783287, 2033.24892985,
       2035.48741862, 2035.45327555, 2028.70600993, 2022.06901449,
       2016.09039714, 2020.27032471, 2027.47960205, 2029.96562

In [28]:
I = data[:1377, 8]
I

array([2042.95495605, 2044.49157715, 2033.0880127 , ..., 2042.83972168,
       2045.87585449, 2051.13476562])

In [29]:
sc.stats.ks_2samp(B, A, alternative='two-sided')

KstestResult(statistic=0.6521673083470836, pvalue=3.776664798435968e-27)

In [30]:
sc.stats.ks_2samp(C, I, alternative='two-sided')

KstestResult(statistic=0.3165633204848891, pvalue=5.003637953748807e-06)

In [31]:
sc.stats.ks_2samp(F, D, alternative='two-sided')

KstestResult(statistic=0.4859085375657487, pvalue=2.020605904817785e-14)

In [32]:
sc.stats.ks_2samp(G, E, alternative='two-sided')

KstestResult(statistic=0.18055874473784922, pvalue=0.027486898055065878)

In [33]:
sc.stats.ks_2samp(H, E, alternative='two-sided')

KstestResult(statistic=0.12950631458094145, pvalue=0.21638384773003738)